import { useState, useCallback, useEffect } from 'react';
import type { Path, Pattern, PracticeEvent, ScheduledOccurrence, RevisitPace } from '@/types/fixation';
import { BASE_INTERVALS, PACE_MULTIPLIERS } from '@/types/fixation';
import { format, addDays, parseISO } from 'date-fns';

function loadFromStorage<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : fallback;
  } catch {
    return fallback;
  }
}

function saveToStorage<T>(key: string, data: T) {
  localStorage.setItem(key, JSON.stringify(data));
}

function generateId() {
  return Math.random().toString(36).slice(2, 10);
}

export function useFixationStore() {
  const [paths, setPaths] = useState<Path[]>(() => loadFromStorage('fixation_paths', []));
  const [patterns, setPatterns] = useState<Pattern[]>(() => loadFromStorage('fixation_patterns', []));
  const [events, setEvents] = useState<PracticeEvent[]>(() => loadFromStorage('fixation_events', []));
  const [scheduled, setScheduled] = useState<ScheduledOccurrence[]>(() => loadFromStorage('fixation_scheduled', []));
  const [pace, setPace] = useState<RevisitPace>(() => loadFromStorage('fixation_pace', 'standard'));

  useEffect(() => saveToStorage('fixation_paths', paths), [paths]);
  useEffect(() => saveToStorage('fixation_patterns', patterns), [patterns]);
  useEffect(() => saveToStorage('fixation_events', events), [events]);
  useEffect(() => saveToStorage('fixation_scheduled', scheduled), [scheduled]);
  useEffect(() => saveToStorage('fixation_pace', pace), [pace]);

  const addPath = useCallback((name: string, intention?: string, color?: string) => {
    const path: Path = { id: generateId(), name, intention, color };
    setPaths(prev => [...prev, path]);
    return path;
  }, []);

  const addPattern = useCallback((name: string, pathId: string) => {
    const pattern: Pattern = { id: generateId(), name, pathId, successCount: 0 };
    setPatterns(prev => [...prev, pattern]);
    return pattern;
  }, []);

  const computeNextDate = useCallback((successCount: number, fixationLevel: 'light' | 'medium' | 'heavy', currentPace: RevisitPace) => {
    if (fixationLevel === 'heavy') return 1;
    const cappedCount = Math.min(successCount, 6);
    const base = cappedCount >= 6 ? 45 : (BASE_INTERVALS[cappedCount] || 1);
    let interval = base * PACE_MULTIPLIERS[currentPace];
    if (fixationLevel === 'medium') interval *= 0.7;
    return Math.max(1, Math.round(interval));
  }, []);

  const logPractice = useCallback((
    patternId: string,
    difficulty: 'easy' | 'medium' | 'hard',
    fixationLevel: 'light' | 'medium' | 'heavy'
  ) => {
    const today = format(new Date(), 'yyyy-MM-dd');
    const event: PracticeEvent = { id: generateId(), date: today, patternId, difficulty, fixationLevel };
    setEvents(prev => [...prev, event]);

    // Increment success count
    setPatterns(prev => prev.map(p =>
      p.id === patternId ? { ...p, successCount: p.successCount + 1 } : p
    ));

    // Remove old scheduled for this pattern
    setScheduled(prev => prev.filter(s => s.patternId !== patternId));

    // Get updated success count
    const pattern = patterns.find(p => p.id === patternId);
    const newSuccess = (pattern?.successCount || 0) + 1;
    const daysUntil = computeNextDate(newSuccess, fixationLevel, pace);
    const nextDate = format(addDays(new Date(), daysUntil), 'yyyy-MM-dd');

    const occurrence: ScheduledOccurrence = {
      id: generateId(),
      date: nextDate,
      patternId,
      autoGenerated: true,
    };
    setScheduled(prev => [...prev, occurrence]);

    return { event, occurrence };
  }, [patterns, pace, computeNextDate]);

  const skipToday = useCallback((patternId: string) => {
    const tomorrow = format(addDays(new Date(), 1), 'yyyy-MM-dd');
    setScheduled(prev => {
      const filtered = prev.filter(s => s.patternId !== patternId);
      return [...filtered, { id: generateId(), date: tomorrow, patternId, autoGenerated: true }];
    });
  }, []);

  const getTodayScheduled = useCallback(() => {
    const today = format(new Date(), 'yyyy-MM-dd');
    return scheduled
      .filter(s => s.date <= today)
      .map(s => ({
        ...s,
        pattern: patterns.find(p => p.id === s.patternId),
        path: paths.find(pa => pa.id === patterns.find(p => p.id === s.patternId)?.pathId),
      }));
  }, [scheduled, patterns, paths]);

  const getScheduledForDate = useCallback((date: string) => {
    return scheduled
      .filter(s => s.date === date)
      .map(s => ({
        ...s,
        pattern: patterns.find(p => p.id === s.patternId),
        path: paths.find(pa => pa.id === patterns.find(p => p.id === s.patternId)?.pathId),
      }));
  }, [scheduled, patterns, paths]);

  return {
    paths, patterns, events, scheduled, pace,
    addPath, addPattern, logPractice, skipToday,
    getTodayScheduled, getScheduledForDate, setPace,
  };
}
