import { useState, useCallback, useEffect, useRef } from 'react';
import type { Path, Pattern, Problem, PracticeEvent, ScheduledOccurrence, RevisitPace } from '@/types/fixation';
import { BASE_INTERVALS, PACE_MULTIPLIERS } from '@/types/fixation';
import { format, addDays } from 'date-fns';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from './useAuth';

function generateId() {
  return crypto.randomUUID();
}

export function useFixationStore() {
  const { user } = useAuth();
  const [paths, setPaths] = useState<Path[]>([]);
  const [patterns, setPatterns] = useState<Pattern[]>([]);
  const [problems, setProblems] = useState<Problem[]>([]);
  const [events, setEvents] = useState<PracticeEvent[]>([]);
  const [scheduled, setScheduled] = useState<ScheduledOccurrence[]>([]);
  const [pace, setPaceState] = useState<RevisitPace>('standard');
  const [loading, setLoading] = useState(true);
  const loadedRef = useRef(false);

  // Load all data from Supabase on mount / user change
  useEffect(() => {
    if (!user) {
      setPaths([]);
      setPatterns([]);
      setProblems([]);
      setEvents([]);
      setScheduled([]);
      setPaceState('standard');
      setLoading(false);
      loadedRef.current = false;
      return;
    }

    const load = async () => {
      setLoading(true);
      const [pathsRes, patternsRes, problemsRes, eventsRes, scheduledRes, prefsRes] = await Promise.all([
        supabase.from('paths').select('*').eq('user_id', user.id),
        supabase.from('patterns').select('*').eq('user_id', user.id),
        supabase.from('problems').select('*').eq('user_id', user.id),
        supabase.from('practice_events').select('*').eq('user_id', user.id),
        supabase.from('scheduled_occurrences').select('*').eq('user_id', user.id),
        supabase.from('user_preferences').select('*').eq('user_id', user.id).maybeSingle(),
      ]);

      setPaths((pathsRes.data || []).map((r: any) => ({ id: r.id, name: r.name, intention: r.intention, color: r.color })));
      setPatterns((patternsRes.data || []).map((r: any) => ({ id: r.id, name: r.name, pathId: r.path_id, successCount: r.success_count, practiceSetCount: r.practice_set_count })));
      setProblems((problemsRes.data || []).map((r: any) => ({ id: r.id, patternId: r.pattern_id, name: r.name, date: r.date })));
      setEvents((eventsRes.data || []).map((r: any) => ({ id: r.id, date: r.date, patternId: r.pattern_id, difficulty: r.difficulty, fixationLevel: r.fixation_level, problemName: r.problem_name })));
      setScheduled((scheduledRes.data || []).map((r: any) => ({ id: r.id, date: r.date, patternId: r.pattern_id, autoGenerated: r.auto_generated })));
      setPaceState((prefsRes.data?.pace as RevisitPace) || 'standard');
      setLoading(false);
      loadedRef.current = true;
    };

    load();
  }, [user]);

  const addPath = useCallback(async (name: string, intention?: string, color?: string) => {
    const id = generateId();
    const path: Path = { id, name, intention, color };
    setPaths(prev => [...prev, path]);

    if (user) {
      await supabase.from('paths').insert({ id, user_id: user.id, name, intention, color } as any);
    }
    return path;
  }, [user]);

  const addPattern = useCallback(async (name: string, pathId: string, practiceSetCount: number = 5) => {
    const id = generateId();
    const pattern: Pattern = { id, name, pathId, successCount: 0, practiceSetCount };
    setPatterns(prev => [...prev, pattern]);

    if (user) {
      await supabase.from('patterns').insert({ id, user_id: user.id, path_id: pathId, name, practice_set_count: practiceSetCount } as any);
    }
    return pattern;
  }, [user]);

  const deletePattern = useCallback(async (patternId: string) => {
    setPatterns(prev => prev.filter(p => p.id !== patternId));
    setScheduled(prev => prev.filter(s => s.patternId !== patternId));
    setProblems(prev => prev.filter(p => p.patternId !== patternId));
    setEvents(prev => prev.filter(e => e.patternId !== patternId));

    if (user) {
      await supabase.from('patterns').delete().eq('id', patternId).eq('user_id', user.id);
    }
  }, [user]);

  const addProblem = useCallback(async (patternId: string, name: string) => {
    const id = generateId();
    const dateStr = format(new Date(), 'yyyy-MM-dd');
    const problem: Problem = { id, patternId, name, date: dateStr };
    setProblems(prev => [...prev, problem]);

    if (user) {
      await supabase.from('problems').insert({ id, user_id: user.id, pattern_id: patternId, name, date: dateStr } as any);
    }
    return problem;
  }, [user]);

  const getProblemsForPattern = useCallback((patternId: string) => {
    return problems.filter(p => p.patternId === patternId);
  }, [problems]);

  const searchPatterns = useCallback((query: string) => {
    if (!query.trim()) return patterns;
    const lower = query.toLowerCase();
    return patterns.filter(p => p.name.toLowerCase().includes(lower));
  }, [patterns]);

  const computeInterval = useCallback((successCount: number, currentPace: RevisitPace) => {
    const cappedCount = Math.min(successCount, 6);
    const base = cappedCount >= 6 ? 45 : (BASE_INTERVALS[cappedCount] || 1);
    return Math.max(1, Math.round(base * PACE_MULTIPLIERS[currentPace]));
  }, []);

  const bookAllFutureOccurrences = useCallback((
    patternId: string,
    currentSuccessCount: number,
    practiceSetCount: number,
    currentPace: RevisitPace,
    fixationLevel: 'light' | 'medium' | 'heavy',
    referenceDate?: Date,
    occupiedDates?: Set<string>,
  ): ScheduledOccurrence[] => {
    const occurrences: ScheduledOccurrence[] = [];
    let cursor = referenceDate || new Date();
    const occupied = occupiedDates ? new Set(occupiedDates) : new Set<string>();

    const startFrom = currentSuccessCount + 1;
    const maxCount = Math.max(practiceSetCount, 6) + 1;

    for (let i = startFrom; i <= maxCount; i++) {
      const days = i === startFrom && fixationLevel === 'heavy'
        ? 1
        : fixationLevel === 'medium'
          ? Math.max(1, Math.round(computeInterval(i, currentPace) * 0.7))
          : computeInterval(i, currentPace);

      cursor = addDays(cursor, days);
      let dateStr = format(cursor, 'yyyy-MM-dd');

      while (occupied.has(dateStr)) {
        cursor = addDays(cursor, 1);
        dateStr = format(cursor, 'yyyy-MM-dd');
      }

      occupied.add(dateStr);
      occurrences.push({
        id: generateId(),
        date: dateStr,
        patternId,
        autoGenerated: true,
      });
    }

    return occurrences;
  }, [computeInterval]);

  const logPractice = useCallback(async (
    patternId: string,
    difficulty: 'easy' | 'medium' | 'hard',
    fixationLevel: 'light' | 'medium' | 'heavy',
    problemName?: string,
    dateStr?: string,
    practiceSetCountOverride?: number,
  ) => {
    const logDate = dateStr || format(new Date(), 'yyyy-MM-dd');
    const referenceDate = dateStr ? new Date(dateStr + 'T00:00:00') : new Date();

    const eventId = generateId();
    const event: PracticeEvent = { id: eventId, date: logDate, patternId, difficulty, fixationLevel, problemName };
    setEvents(prev => [...prev, event]);

    if (problemName?.trim()) {
      const probId = generateId();
      const problem: Problem = { id: probId, patternId, name: problemName.trim(), date: logDate };
      setProblems(prev => [...prev, problem]);
      if (user) {
        supabase.from('problems').insert({ id: probId, user_id: user.id, pattern_id: patternId, name: problemName.trim(), date: logDate } as any).then(() => {});
      }
    }

    setPatterns(prev => prev.map(p =>
      p.id === patternId ? {
        ...p,
        successCount: p.successCount + 1,
        ...(practiceSetCountOverride != null ? { practiceSetCount: practiceSetCountOverride } : {}),
      } : p
    ));

    const pattern = patterns.find(p => p.id === patternId);
    const effectivePSC = practiceSetCountOverride ?? pattern?.practiceSetCount ?? 5;
    const newSuccess = (pattern?.successCount || 0) + 1;

    // Compute new schedule
    let newScheduled: ScheduledOccurrence[] = [];
    setScheduled(prev => {
      let removedOne = false;
      const filtered = prev.filter(s => {
        if (!removedOne && s.patternId === patternId && s.date <= logDate) {
          removedOne = true;
          return false;
        }
        return true;
      });

      const occupiedDates = new Set<string>();
      for (const s of filtered) occupiedDates.add(s.date);

      const futureOccurrences = bookAllFutureOccurrences(patternId, newSuccess, effectivePSC, pace, fixationLevel, referenceDate, occupiedDates);
      newScheduled = futureOccurrences;
      return [...filtered, ...futureOccurrences];
    });

    // Persist to Supabase
    if (user) {
      await supabase.from('practice_events').insert({ id: eventId, user_id: user.id, pattern_id: patternId, date: logDate, difficulty, fixation_level: fixationLevel, problem_name: problemName } as any);
      await supabase.from('patterns').update({ success_count: newSuccess, ...(practiceSetCountOverride != null ? { practice_set_count: practiceSetCountOverride } : {}) } as any).eq('id', patternId).eq('user_id', user.id);

      // Replace all scheduled for this pattern
      await supabase.from('scheduled_occurrences').delete().eq('pattern_id', patternId).eq('user_id', user.id);
      // Get current scheduled for this pattern from state
      // We need to insert the new ones
      const allForPattern = await new Promise<ScheduledOccurrence[]>(resolve => {
        setScheduled(prev => {
          resolve(prev.filter(s => s.patternId === patternId));
          return prev;
        });
      });
      if (allForPattern.length > 0) {
        await supabase.from('scheduled_occurrences').insert(
          allForPattern.map(s => ({ id: s.id, user_id: user.id, pattern_id: s.patternId, date: s.date, auto_generated: s.autoGenerated } as any))
        );
      }
    }

    const futureOccurrences = bookAllFutureOccurrences(patternId, newSuccess, effectivePSC, pace, fixationLevel, referenceDate);
    return { event, occurrence: futureOccurrences[0] || { id: '', date: format(addDays(referenceDate, 1), 'yyyy-MM-dd'), patternId, autoGenerated: true } };
  }, [patterns, pace, bookAllFutureOccurrences, user]);

  const skipToday = useCallback(async (patternId: string) => {
    const tomorrow = format(addDays(new Date(), 1), 'yyyy-MM-dd');
    const newId = generateId();

    setScheduled(prev => {
      const filtered = prev.filter(s => s.patternId !== patternId);
      return [...filtered, { id: newId, date: tomorrow, patternId, autoGenerated: true }];
    });

    if (user) {
      await supabase.from('scheduled_occurrences').delete().eq('pattern_id', patternId).eq('user_id', user.id);
      await supabase.from('scheduled_occurrences').insert({ id: newId, user_id: user.id, pattern_id: patternId, date: tomorrow, auto_generated: true } as any);
    }
  }, [user]);

  const getTodayScheduled = useCallback(() => {
    const today = format(new Date(), 'yyyy-MM-dd');
    return scheduled
      .filter(s => s.date <= today)
      .map(s => ({
        ...s,
        pattern: patterns.find(p => p.id === s.patternId),
        path: paths.find(pa => pa.id === patterns.find(p => p.id === s.patternId)?.pathId),
      }));
  }, [scheduled, patterns, paths]);

  const getScheduledForDate = useCallback((date: string) => {
    return scheduled
      .filter(s => s.date === date)
      .map(s => ({
        ...s,
        pattern: patterns.find(p => p.id === s.patternId),
        path: paths.find(pa => pa.id === patterns.find(p => p.id === s.patternId)?.pathId),
      }));
  }, [scheduled, patterns, paths]);

  const getEventsForDate = useCallback((date: string) => {
    return events
      .filter(e => e.date === date)
      .map(e => ({
        ...e,
        pattern: patterns.find(p => p.id === e.patternId),
        path: paths.find(pa => pa.id === patterns.find(p => p.id === e.patternId)?.pathId),
      }));
  }, [events, patterns, paths]);

  const setPace = useCallback(async (newPace: RevisitPace) => {
    setPaceState(newPace);
    if (user) {
      await supabase.from('user_preferences').upsert({ user_id: user.id, pace: newPace } as any);
    }
  }, [user]);

  const resetForTesting = useCallback(async () => {
    setEvents([]);
    setProblems([]);
    setScheduled([]);
    setPatterns(prev => prev.map(p => ({ ...p, successCount: 0 })));

    if (user) {
      await Promise.all([
        supabase.from('practice_events').delete().eq('user_id', user.id),
        supabase.from('problems').delete().eq('user_id', user.id),
        supabase.from('scheduled_occurrences').delete().eq('user_id', user.id),
      ]);
      // Reset success counts
      const { data: pats } = await supabase.from('patterns').select('id').eq('user_id', user.id);
      if (pats) {
        for (const p of pats) {
          await supabase.from('patterns').update({ success_count: 0 } as any).eq('id', p.id);
        }
      }
    }
  }, [user]);

  return {
    paths, patterns, problems, events, scheduled, pace, loading,
    addPath, addPattern, deletePattern, addProblem,
    getProblemsForPattern, searchPatterns,
    logPractice, skipToday,
    getTodayScheduled, getScheduledForDate, getEventsForDate, setPace,
    resetForTesting,
  };
}
