export interface Path {
  id: string;
  name: string;
  intention?: string;
  color?: string;
}

export interface Pattern {
  id: string;
  name: string;
  pathId: string;
  successCount: number;
  practiceSetCount: number; // default 5
}

export interface Problem {
  id: string;
  patternId: string;
  name: string;
  date: string; // YYYY-MM-DD
}

export interface PracticeEvent {
  id: string;
  date: string; // YYYY-MM-DD
  patternId: string;
  difficulty: 'easy' | 'medium' | 'hard';
  fixationLevel: 'light' | 'medium' | 'heavy';
  problemName?: string;
}

export interface ScheduledOccurrence {
  id: string;
  date: string; // YYYY-MM-DD
  patternId: string;
  autoGenerated: boolean;
}

export type RevisitPace = 'gentle' | 'standard' | 'intensive';
export type ViewMode = 'daily' | 'weekly' | 'monthly';

export const AFFIRMATIONS = [
  "One concept. One layer deeper.",
  "Return gently. Understand fully.",
  "You've been here before. Go further.",
  "Repetition isn't repetition. It's refinement.",
  "Let the pattern settle in its own time.",
  "Your understanding compounds silently.",
  "Nothing is wasted. Every revisit counts.",
];

export const BASE_INTERVALS: Record<number, number> = {
  1: 1,
  2: 3,
  3: 7,
  4: 14,
  5: 30,
};

export const PACE_MULTIPLIERS: Record<RevisitPace, number> = {
  gentle: 1.5,
  standard: 1.0,
  intensive: 0.7,
};
